### ISSUE TITLE
Heroku Static Error Page

### ISSUE THREAD

**Issue by OhmGeek** [AidansJCR/aidans-jcr#19]
When we want to enable Heroku maintenance, or a server error occurs, we will currently just see a Heroku error page. 

Instead, we can fairly easily use a custom error page. Therefore, make them, place them onto S3, and then set the correct ENV variables to get them to Display.

**Comment by OhmGeek** [comment]
These need to be HTML files. Literally just with the logo, and some error report (without menus).
Mostly for when the server is down, or when we've managed to crash the system badly.

**Comment by CADuffy** [comment]
I've added a simple but custom Heroku maintenance page and it is now being served correctly. Once I've styled it a bit more the other pages can use the same template with slightly different content.

**Comment by OhmGeek** [comment]
That's perfect, this is fixed now then :+1:
